### ISSUE TITLE
Prints first line of file when reloading python files

### ISSUE THREAD

**Issue by matthijskooijman** [Raimondi/yaifa#7]
I've noticed that when reloading a python file (or also when navigating through the history), yaifa causes the first line of the file to be printed. To reproduce, simply open up any non-empty python file, and do `:e`.

For this to work, filetype plugins must be on, but removing my custom python ftplugin does not fix this, so that is probably not it. Removing all my `.vimrc` except `filetype plugin on` and removing all plugins except yaifa does not help either.

Tracing this in the code, it is somehow caused by this line:

https://github.com/Raimondi/yaifa/blob/72998c424d4c5ca5c9831173c38e300660740e33/autoload/yaifa.vim#L312

I'm not actually sure what that says or is supposed to do, but removing it fixes the problem. This line was introduced in 93b2c0efc30a25bfac18b55d42a7fbdae534aea7, but that says to only move code, but the line was not present in the old file, so that does not really help me.

I thought that the `\` might be intended as a line continuation, but putting it at the end of the previous line gives errors, and removing it and just joining the lines does not fix the problem...

I'm just going to try removing that line for now and see what happens.

**Comment by matthijskooijman** [comment]
Thanks for fixing (this and the other issue), seems to work fine here. From your fix, I think I understand the problem better, looks like a good fix :-)

**Comment by Raimondi** [comment]
Thanks for reporting the issue, I hadn't noticed it before.
